# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
# Or not, since I'm using figaro anyway

development:
  secret_key_base: bc1edf256dbfbee7e77d80201843722d541ea06a556fcd978d37a5990bda3876ccd5e2f6eb19ba877872a524baa48d05f8cf325ab10547ee3a6c5d9bd8db7bff

test:
  secret_key_base: e99203b51dafb930db4a99c0263cf3ba0e7d7bd813809003c8c407af207c8312ab87a249bbb42861d72178aa3939d77103c5cc06ce25fa9af84644ebf239fa10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
